### ISSUE TITLE
skextremes.models.classic.GEV bootstrap number of samples

### ISSUE THREAD

**Issue by michelucci** [kikocorreoso/scikit-extremes#13]
Hallo,

first of all thank you for your package. Is great. I have a question. I use the following line

`model = ske.models.classic.GEV(max_list, fit_method = 'mle', ci = 0.05, ci_method = 'bootstrap')`

I was wondering how many bootstrap samples are used for the confidence intervals and if one can set the number. 
Thanks, Umberto

**Comment by kikocorreoso** [comment]
Hi,

The number of samples is hardcoded here (500 samples): https://github.com/kikocorreoso/scikit-extremes/blob/master/skextremes/models/classic.py#L602

It should be relatively easy to update the base class (IIRC) to accept a parameter with the number of samples to use. If you want to send a PR I could review it.

I close the issue as this is not an issue. We can continue the discussion here: https://github.com/kikocorreoso/scikit-extremes/discussions
