### ISSUE TITLE
pip cant install scikit-extremes

### ISSUE THREAD

**Issue by mada0007** [kikocorreoso/scikit-extremes#4]
I try to install and I get this error
pip install scikit-extremes
Collecting scikit-extremes
  Could not find a version that satisfies the requirement scikit-extremes (from versions: )
No matching distribution found for scikit-extremes

**Comment by kikocorreoso** [comment]
`scikit-extremes` is not on PyPI as it is not production ready. One day I will find some time to work on it...

To install it follow the instructions here:

https://github.com/kikocorreoso/scikit-extremes#installation

If you find an issue just open a new one.
