### ISSUE TITLE
Lieblin For n>16

### ISSUE THREAD

**Issue by FredWrecked** [kikocorreoso/scikit-extremes#5]
I'm working with extreme wind speeds. I'm comparing the impact  of different fitting procedures and am fining the Lieblin BLUE technique to be performing well. I'm a phd student and still fairly new to extreme value theory and python in general. 

I was wondering  how you deal with sample sizes greater than 16, I know (Lieblin, 1974) only derived tables of coefficients for  n up to 16 . I see in the code there's a separate procedure using the hypergeometric distribution, would you be able to provide me with a reference as to how this is done?

This tool has helped me so much, thank you.

**Comment by kikocorreoso** [comment]
Hi,

Sorry for the delayed answer. Too much travelling last weeks.

You can read about the procedure developed by Lieblein [here](https://ia601301.us.archive.org/28/items/efficientmethods7460lieb/efficientmethods7460lieb.pdf). All what is coded in `scikit-extremes` is extracted from the previous link. In the paper you have examples for samples with more than 16 values.

It is great the library is useful. It would be great if you share your advances with extreme value theory.
