### ISSUE TITLE
How to install scikit-extreme?

### ISSUE THREAD

**Issue by Paresh1309** [kikocorreoso/scikit-extremes#6]
I tried to install scikit-extremes and I get this error 
pip install scikit-extremes
 Collecting scikit-extremes
 Could not find a version that satisfies the requirement scikit-extremes (from versions: ) 
No matching distribution found for scikit-extremes 
.
please help me in installing scikit-extreme by giving step-by-step procedure to install.

**Comment by kikocorreoso** [comment]
Please, read here: https://github.com/kikocorreoso/scikit-extremes#installation

You will need to have python, pip and git installed. It is not uploaded to PyPI so it is not possible to use `pip install` directly at this moment.
